config/routes.rb
Rails.application.routes.draw do
  resources :type_documents
  devise_for :users
  
  resources :cities
  resources :departments
  resources :countries
  resources :clients
  
  root :to => 'clients#index'
  # devise_for :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/type_document.rb
class TypeDocument
  include Mongoid::Document
  has_many :typeDocuments
  
  field :name, type: String
  field :type, type: Integer
end

app/controllers/type_documents_controller.rb
class TypeDocumentsController < ApplicationController
  before_action :set_type_document, only: [:show, :edit, :update, :destroy]

  # GET /type_documents
  # GET /type_documents.json
  def index
    @type_documents = TypeDocument.all
  end

  # GET /type_documents/1
  # GET /type_documents/1.json
  def show
  end

  # GET /type_documents/new
  def new
    @type_document = TypeDocument.new
  end

  # GET /type_documents/1/edit
  def edit
  end

  # POST /type_documents
  # POST /type_documents.json
  def create
    @type_document = TypeDocument.new(type_document_params)

    respond_to do |format|
      if @type_document.save
        format.html { redirect_to @type_document, notice: 'Type document was successfully created.' }
        format.json { render :show, status: :created, location: @type_document }
      else
        format.html { render :new }
        format.json { render json: @type_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_documents/1
  # PATCH/PUT /type_documents/1.json
  def update
    respond_to do |format|
      if @type_document.update(type_document_params)
        format.html { redirect_to @type_document, notice: 'Type document was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_document }
      else
        format.html { render :edit }
        format.json { render json: @type_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_documents/1
  # DELETE /type_documents/1.json
  def destroy
    @type_document.destroy
    respond_to do |format|
      format.html { redirect_to type_documents_url, notice: 'Type document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_document
      @type_document = TypeDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_document_params
      params.require(:type_document).permit(:name, :type)
    end
end

app/helpers/type_documents_helper.rb
module TypeDocumentsHelper
end

app/views/type_documents/_form.html.erb
<%= form_with(model: type_document, local: true) do |form| %>
  <% if type_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_document.errors.count, "error") %> prohibited this type_document from being saved:</h2>

      <ul>
      <% type_document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :type_document_name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.number_field :type, id: :type_document_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/type_documents/edit.html.erb
<h1>Editing Type Document</h1>

<%= render 'form', type_document: @type_document %>

<%= link_to 'Show', @type_document %> |
<%= link_to 'Back', type_documents_path %>

app/views/type_documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_documents.each do |type_document| %>
      <tr>
        <td><%= type_document.name %></td>
        <td><%= type_document.type %></td>
        <td><%= link_to 'Show', type_document %></td>
        <td><%= link_to 'Edit', edit_type_document_path(type_document) %></td>
        <td><%= link_to 'Destroy', type_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Document', new_type_document_path %>

app/views/type_documents/new.html.erb
<h1>New Type Document</h1>

<%= render 'form', type_document: @type_document %>

<%= link_to 'Back', type_documents_path %>

app/views/type_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_document.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @type_document.type %>
</p>

<%= link_to 'Edit', edit_type_document_path(@type_document) %> |
<%= link_to 'Back', type_documents_path %>