config/routes.rb
Rails.application.routes.draw do
  resources :type_documents
  devise_for :users
  
  resources :cities
  resources :departments
  resources :countries
  resources :clients
  
  root :to => 'clients#index'
  # devise_for :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clients</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav>
      <div class="nav-wrapper">
        
        <a  class="brand-logo"><%= image_tag "cat.png", style: "width: 50% !important; margin-left: 10% !important;" %></a>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
             <li><%= link_to I18n.t('actions.clients'), clients_path %></li>
             <li><%= link_to I18n.t('actions.cities'), cities_path %></li>
             <li><%= link_to I18n.t('actions.departments'), departments_path %></li>
             <li><%= link_to I18n.t('actions.log_out'), destroy_user_session_path, :method => :delete %></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <link href="http://materializecss.com/css/ghpages-materialize.css" rel="stylesheet">

  </head>

  <body>
    
    
    <main>
      <div class="section no-pad-bot cover">
        <div class="container">
          <div class="row center">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
      
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clients</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
      <div style="background-color:pink; color: blue; width: 100%; height: 500px;">
          <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
      </div>
    <%= yield %>
    <div style="background-color:pink; color: blue; width: 100%; height: 500px;">kokooookokokokokokokkooko</div>
  </body>
</html>